version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    networks:
      - backend-network
    volumes:
      - mongo-db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_secret

  app:
    build: ./app
    restart: always
    ports:
      - "4433:4433"
    volumes:
      - ./app:/app
    networks:
      - backend-network
    depends_on:
      - mongo

networks:
  backend-network:

volumes:
    mongo-db-data: